// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZZ3H4rHXRph3bu5sAC9b5oUKIIb7jhE',
    appId: '1:762535880084:web:6223299fd927d4d134db81',
    messagingSenderId: '762535880084',
    projectId: 'altfit-23631',
    authDomain: 'altfit-23631.firebaseapp.com',
    storageBucket: 'altfit-23631.firebasestorage.app',
    measurementId: 'G-HTTM3CJRLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD527Er3y2a1gyPpLRXpLPH5O0zYmbV2k',
    appId: '1:762535880084:android:5cdd6a418aaa07e134db81',
    messagingSenderId: '762535880084',
    projectId: 'altfit-23631',
    storageBucket: 'altfit-23631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR87cU-m_7T1qvXs-YCq2AydB2oWRu8WE',
    appId: '1:762535880084:ios:77f9ce4819a55f9034db81',
    messagingSenderId: '762535880084',
    projectId: 'altfit-23631',
    storageBucket: 'altfit-23631.firebasestorage.app',
    iosBundleId: 'com.example.altfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR87cU-m_7T1qvXs-YCq2AydB2oWRu8WE',
    appId: '1:762535880084:ios:77f9ce4819a55f9034db81',
    messagingSenderId: '762535880084',
    projectId: 'altfit-23631',
    storageBucket: 'altfit-23631.firebasestorage.app',
    iosBundleId: 'com.example.altfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZZ3H4rHXRph3bu5sAC9b5oUKIIb7jhE',
    appId: '1:762535880084:web:46cffba8446eb0fe34db81',
    messagingSenderId: '762535880084',
    projectId: 'altfit-23631',
    authDomain: 'altfit-23631.firebaseapp.com',
    storageBucket: 'altfit-23631.firebasestorage.app',
    measurementId: 'G-0XQL1Z76FD',
  );
}
